services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $googleIdentityPlatformConfig: '%sfs_user.login.google_identity_platform%'

    Softspring\UserBundle\Controller\GoogleIdentityPlatformLoginController:
        public: true

    Softspring\UserBundle\GoogleIdentityPlatform\IdentityPlatformGoogleAuthenticator:
        arguments:
            $apiKey: '%sfs_user.login.google_identity_platform.api_key%'
            $tenantId: '%sfs_user.login.google_identity_platform.tenant_id%'

    Softspring\UserBundle\GoogleIdentityPlatform\IdentityPlatformUserSynchronizer: ~

    Softspring\UserBundle\Manager\IdentityPlatformSessionManager:
        arguments:
            $apiKey: '%sfs_user.login.google_identity_platform.api_key%'
            $tenantId: '%sfs_user.login.google_identity_platform.tenant_id%'

    Softspring\UserBundle\Manager\IdentityPlatformSessionManagerInterface:
        alias: Softspring\UserBundle\Manager\IdentityPlatformSessionManager

    Softspring\UserBundle\Security\IdentityPlatformAccessTokenHandler: ~
