services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Softspring\UserBundle\Manipulator\UserAccessManipulator: ~
    Softspring\UserBundle\EventListener\UserAccessEventSubscriber: ~

    Softspring\UserBundle\Manager\UserAccessManagerInterface:
        class: Softspring\UserBundle\Manager\UserAccessManager