services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $inviteClass: '%sfs_user.invite.class%'

    Softspring\UserBundle\Mailer\Loader\MailTemplateLoader:
        tags: [ 'sfs_mailer.template_loader' ]