services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Softspring\UserBundle\Mailer\UserMailerInterface:
        class: Softspring\UserBundle\Mailer\UserMailer

    Softspring\UserBundle\EventListener\SendResetPasswordEmailListener: ~
    Softspring\UserBundle\EventListener\UserRegistrationListener: ~
