security:
    role_hierarchy:
        SFS_USER_ROLE_ADMIN_USERS_RO:
            - SFS_USER_PERMISSION_ADMIN_USERS_LIST
            - SFS_USER_PERMISSION_ADMIN_USERS_DETAILS
        SFS_USER_ROLE_ADMIN_USERS_RW:
            - SFS_USER_PERMISSION_ADMIN_USERS_DELETE
            - SFS_USER_PERMISSION_ADMIN_USERS_PROMOTE
            - SFS_USER_PERMISSION_ADMIN_USERS_UPDATE
        SFS_USER_ROLE_ADMIN_ADMINISTRATORS_RO:
            - SFS_USER_PERMISSION_ADMIN_ADMINISTRATORS_LIST
            - SFS_USER_PERMISSION_ADMIN_ADMINISTRATORS_DETAILS
        SFS_USER_ROLE_ADMIN_ADMINISTRATORS_RW:
            - SFS_USER_PERMISSION_ADMIN_ADMINISTRATORS_DEMOTE
            - SFS_USER_PERMISSION_ADMIN_ADMINISTRATORS_UPDATE
            - SFS_USER_PERMISSION_ADMIN_ADMINISTRATORS_DELETE