services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $changeEmailConfig: []
            $changeUsernameConfig: []
            $firewallMap: '@security.firewall.map'
            $impersonateBarConfig: '%sfs_user.impersonate_bar%'
            $em: '@sfs_user.entity_manager'
            $resetTokenTTL: '%sfs_user.reset_password.token_ttl%'

    Softspring\UserBundle\Command\:
        resource: '../../Command/*'

    Softspring\UserBundle\Controller\:
        resource: '../../Controller/*'
        public: true

    Softspring\UserBundle\EventListener\AutoAuthenticateEventSubscriber: ~
    Softspring\UserBundle\EventListener\ImpersonateBarListener: ~
    Softspring\UserBundle\EventListener\EmailInvitationListener: ~
    Softspring\UserBundle\EventListener\LastLoginEventSubscriber: ~
    Softspring\UserBundle\EventListener\SendResetPasswordEmailListener: ~

    Softspring\UserBundle\Form\:
        resource: '../../Form/*'

    Softspring\User\Mailer\MailerInterface:
        class: Softspring\UserBundle\Mailer\MailerTemplate

    Softspring\User\Manager\UserAccessManagerInterface:
        class: Softspring\UserBundle\Manager\UserAccessManager

    Softspring\User\Manager\UserInvitationManagerInterface:
        class: Softspring\UserBundle\Manager\UserInvitationManager

    Softspring\User\Manager\UserManagerInterface:
        class: Softspring\UserBundle\Manager\UserManager

    Softspring\UserBundle\Manipulator\UserInvitationManipulator: ~
    Softspring\UserBundle\Manipulator\UserManipulator: ~

    Softspring\UserBundle\Provider\:
        resource: '../../Provider/*'

    Softspring\UserBundle\Security\:
        resource: '../../Security/*'

    Softspring\User\Util\:
        resource: '../../../user/Util/*'

    # tags
    Softspring\UserBundle\Mailer\Loader\MailTemplateLoader:
        tags: ['sfs_mailer.template_loader']

    # service aliases
    sfs_user.user_provider: '@Softspring\UserBundle\Provider\UserProvider'
    sfs_user.user_provider.email: '@Softspring\UserBundle\Provider\EmailProvider'
    sfs_user.user_provider.username: '@Softspring\UserBundle\Provider\UsernameProvider'