services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
#            $changeEmailConfig: []
#            $changeUsernameConfig: []
            $locales: '%sfs_core.locales%'
            $firewallMap: '@security.firewall.map'
            $impersonateBarConfig: '%sfs_user.impersonate_bar%'
            $em: '@sfs_user.entity_manager'
            $resetTokenTTL: '%sfs_user.reset_password.token_ttl%'
            $inviteClass: '%sfs_user.invite.class%'
            $oauthServices: '%sfs_user.oauth.services%'
            $targetPathParameter: '%sfs_user.login.target_path_parameter%'

    Softspring\UserBundle\Command\:
        resource: '../../Command/*'

    Softspring\UserBundle\Controller\:
        resource: '../../Controller/*'
        exclude:  '../../Controller/Admin/*'
        public: true

    Softspring\UserBundle\EventListener\Admin\FlashMessagesListener: ~
    Softspring\UserBundle\EventListener\AutoAuthenticateEventSubscriber: ~
    Softspring\UserBundle\EventListener\ImpersonateBarListener: ~
    Softspring\UserBundle\EventListener\EmailInvitationListener: ~
    Softspring\UserBundle\EventListener\LastLoginEventSubscriber: ~
    Softspring\UserBundle\EventListener\SendResetPasswordEmailListener: ~
    Softspring\UserBundle\EventListener\UserRegistrationListener: ~

    Softspring\UserBundle\Form\:
        resource: '../../Form/*'
        exclude:  '../../Form/(Admin,Settings)/*'

    Softspring\UserBundle\Mailer\UserMailerInterface:
        class: Softspring\UserBundle\Mailer\UserMailer

    Softspring\UserBundle\Manager\UserInvitationManagerInterface:
        class: Softspring\UserBundle\Manager\UserInvitationManager

    Softspring\UserBundle\Manager\UserManagerInterface:
        class: Softspring\UserBundle\Manager\UserManager

    Softspring\UserBundle\Manipulator\UserInvitationManipulator: ~
    Softspring\UserBundle\Manipulator\UserManipulator: ~

    Softspring\UserBundle\Provider\:
        resource: '../../Provider/*'

    Softspring\UserBundle\Security\:
        resource: '../../Security/*'

    Softspring\UserBundle\Twig\Extension\:
        resource: '../../Twig/Extension/*'
        tags: ['twig.extension']

    Softspring\UserBundle\Util\:
        resource: '../../Util/*'

    # tags
    Softspring\UserBundle\Mailer\Loader\MailTemplateLoader:
        tags: ['sfs_mailer.template_loader']

    # service aliases
    sfs_user.user_provider: '@Softspring\UserBundle\Provider\UserProvider'
    sfs_user.user_provider.email: '@Softspring\UserBundle\Provider\EmailProvider'
    sfs_user.user_provider.username: '@Softspring\UserBundle\Provider\UsernameProvider'