services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Softspring\UserBundle\Form\Admin\AdministratorInviteForm: ~

    sfs_user.admin.administrator_invite.controller:
        class: Softspring\CrudlBundle\Controller\CrudlController
        public: true
        calls:
            - { method: setContainer, arguments: ['@service_container'] }
        arguments:
            $manager: '@Softspring\UserBundle\Manager\UserInvitationManagerInterface'
            $eventDispatcher: '@event_dispatcher'
            $createForm: '@Softspring\UserBundle\Form\Admin\AdministratorInviteFormInterface'
            $config:
                entity_attribute: 'administrator'
                create:
                    is_granted: 'ROLE_ADMIN_ADMINISTRATORS_INVITE'
                    initialize_event_name: !php/const Softspring\UserBundle\SfsUserEvents::ADMIN_ADMINISTRATORS_INVITE_INITIALIZE
                    form_valid_event_name: !php/const Softspring\UserBundle\SfsUserEvents::ADMIN_ADMINISTRATORS_INVITE_FORM_VALID
                    success_event_name: !php/const Softspring\UserBundle\SfsUserEvents::ADMIN_ADMINISTRATORS_INVITE_SUCCESS
                    form_invalid_event_name: !php/const Softspring\UserBundle\SfsUserEvents::ADMIN_ADMINISTRATORS_INVITE_FORM_INVALID
                    view_event_name: !php/const Softspring\UserBundle\SfsUserEvents::ADMIN_ADMINISTRATORS_INVITE_VIEW
                    success_redirect_to: 'sfs_user_admin_administrators_list'
                    view: '@@SfsUser/admin/administrators/invite.html.twig'