services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Softspring\UserBundle\Form\Admin\:
        resource: '../../../src/Form/Admin/AccessHistory*'

    sfs_user.admin.access_history.controller:
        class: Softspring\Component\CrudlController\Controller\CrudlController
        public: true
        tags: [ 'controller.service_arguments' ]
        arguments:
            $manager: '@Softspring\UserBundle\Manager\UserAccessManagerInterface'
            $eventDispatcher: '@event_dispatcher'
            $config:
                entity_attribute: 'access'
                list:
                    is_granted: 'PERMISSION_SFS_USER_ADMIN_HISTORY_LIST'
                    initialize_event_name: !php/const Softspring\UserBundle\SfsUserEvents::ADMIN_ACCESS_HISTORY_LIST_INITIALIZE
                    view_event_name: !php/const Softspring\UserBundle\SfsUserEvents::ADMIN_ACCESS_HISTORY_LIST_VIEW
                    view: '@@SfsUser/admin/access-history/list.html.twig'
                    view_page: '@@SfsUser/admin/access-history/list-page.html.twig'
                    filter_form: '@Softspring\UserBundle\Form\Admin\AccessHistoryListFilterFormInterface'