services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $impersonateBarConfig: '%sfs_user.impersonate_bar%'
            $locales: '%kernel.enabled_locales%'

    Softspring\UserBundle\Form\Admin\:
        resource: '../../../src/Form/Admin/User*'

    Softspring\UserBundle\EventListener\Admin\:
        resource: '../../../src/EventListener/Admin/User*'

    Softspring\UserBundle\Controller\Admin\UsersController:
        public: true

    sfs_user.admin.user.controller:
        class: Softspring\Component\CrudlController\Controller\CrudlController
        public: true
        tags: [ 'controller.service_arguments' ]
        arguments:
            $manager: '@Softspring\UserBundle\Manager\UserManagerInterface'
            $eventDispatcher: '@event_dispatcher'
            $config:
                entity_attribute: 'user'
                list:
                    is_granted: 'PERMISSION_SFS_USER_ADMIN_USERS_LIST'
                    initialize_event_name: !php/const Softspring\UserBundle\SfsUserEvents::ADMIN_USERS_LIST_INITIALIZE
                    view_event_name: !php/const Softspring\UserBundle\SfsUserEvents::ADMIN_USERS_LIST_VIEW
                    view: '@@SfsUser/admin/users/list.html.twig'
                    view_page: '@@SfsUser/admin/users/list-page.html.twig'
                    entities_attribute: 'users'
                    filter_form: '@Softspring\UserBundle\Form\Admin\UserListFilterFormInterface'
                update:
                    is_granted: 'PERMISSION_SFS_USER_ADMIN_USERS_UPDATE'
                    param_converter_key: 'id'
                    initialize_event_name: !php/const Softspring\UserBundle\SfsUserEvents::ADMIN_USERS_UPDATE_INITIALIZE
                    form_valid_event_name: !php/const Softspring\UserBundle\SfsUserEvents::ADMIN_USERS_UPDATE_FORM_VALID
                    success_event_name: !php/const Softspring\UserBundle\SfsUserEvents::ADMIN_USERS_UPDATE_SUCCESS
                    form_invalid_event_name: !php/const Softspring\UserBundle\SfsUserEvents::ADMIN_USERS_UPDATE_FORM_INVALID
                    view_event_name: !php/const Softspring\UserBundle\SfsUserEvents::ADMIN_USERS_UPDATE_VIEW
                    success_redirect_to: 'sfs_user_admin_users_list'
                    view: '@@SfsUser/admin/users/update.html.twig'
                    form: '@Softspring\UserBundle\Form\Admin\UserUpdateFormInterface'
                delete:
                    is_granted: 'PERMISSION_SFS_USER_ADMIN_USERS_DELETE'
                    param_converter_key: 'id'
                    initialize_event_name: !php/const Softspring\UserBundle\SfsUserEvents::ADMIN_USERS_DELETE_INITIALIZE
                    form_valid_event_name: !php/const Softspring\UserBundle\SfsUserEvents::ADMIN_USERS_DELETE_FORM_VALID
                    success_event_name: !php/const Softspring\UserBundle\SfsUserEvents::ADMIN_USERS_DELETE_SUCCESS
                    form_invalid_event_name: !php/const Softspring\UserBundle\SfsUserEvents::ADMIN_USERS_DELETE_FORM_INVALID
                    view_event_name: !php/const Softspring\UserBundle\SfsUserEvents::ADMIN_USERS_DELETE_VIEW
                    success_redirect_to: 'sfs_user_admin_users_list'
                    view: '@@SfsUser/admin/users/delete.html.twig'
                    form: '@Softspring\UserBundle\Form\Admin\UserDeleteFormInterface'
                read:
                    is_granted: 'PERMISSION_SFS_USER_ADMIN_USERS_DETAILS'
                    param_converter_key: 'id'
                    initialize_event_name: !php/const Softspring\UserBundle\SfsUserEvents::ADMIN_USERS_DETAILS_INITIALIZE
                    view_event_name: !php/const Softspring\UserBundle\SfsUserEvents::ADMIN_USERS_DETAILS_VIEW
                    view: '@@SfsUser/admin/users/details.html.twig'