sfs_user_reset_password_request:
    path: /
    controller: Softspring\UserBundle\Controller\ResetPasswordController::request

sfs_user_reset_password_requested:
    path: /sent
    controller: Softspring\UserBundle\Controller\ResetPasswordController::requested

sfs_user_reset_password:
    path: /{user}/reset/{token}
    controller: Softspring\UserBundle\Controller\ResetPasswordController::reset

sfs_user_reset_password_success:
    path: /success
    controller: Softspring\UserBundle\Controller\ResetPasswordController::success

