services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
#            $changeEmailConfig: []
#            $changeUsernameConfig: []
            $locales: '%kernel.enabled_locales%'
            $firewallMap: '@security.firewall.map'
            $em: '@sfs_user.entity_manager'
            $resetTokenTTL: '%sfs_user.reset_password.token_ttl%'
            $oauthServices: '%sfs_user.oauth.services%'
            $targetPathParameter: '%sfs_user.login.target_path_parameter%'

    Softspring\UserBundle\Command\CreateUserCommand: ~
    Softspring\UserBundle\Command\PromoteUserCommand: ~

    Softspring\UserBundle\Controller\LoginController:
        public: true
    Softspring\UserBundle\Controller\OauthLoginIntegrationController:
        public: true
    Softspring\UserBundle\Controller\RegisterController:
        public: true
    Softspring\UserBundle\Controller\ResetPasswordController:
        public: true
    Softspring\UserBundle\Controller\Settings\ChangeEmailController:
        public: true
    Softspring\UserBundle\Controller\Settings\ChangePasswordController:
        public: true
    Softspring\UserBundle\Controller\Settings\ChangeUsernameController:
        public: true
    Softspring\UserBundle\Controller\Settings\ConfirmationController:
        public: true
    Softspring\UserBundle\Controller\Settings\PreferencesController:
        public: true

    Softspring\UserBundle\EventListener\Admin\FlashMessagesListener: ~
    Softspring\UserBundle\EventListener\AutoAuthenticateEventSubscriber: ~
    Softspring\UserBundle\EventListener\LastLoginEventSubscriber: ~
    Softspring\UserBundle\EventListener\SendResetPasswordEmailListener: ~
    Softspring\UserBundle\EventListener\UserRegistrationListener: ~

    Softspring\UserBundle\Form\:
        resource: '../src/Form/*'
        exclude:  '../src/Form/Admin/'

    Softspring\UserBundle\Mailer\UserMailerInterface:
        class: Softspring\UserBundle\Mailer\UserMailer


    Softspring\UserBundle\Manager\UserManagerInterface:
        class: Softspring\UserBundle\Manager\UserManager

    Softspring\UserBundle\Manipulator\UserManipulator: ~

    Softspring\UserBundle\Provider\:
        resource: '../src/Provider/*'

    Softspring\UserBundle\Security\:
        resource: '../src/Security/*'

    Softspring\UserBundle\Twig\Extension\:
        resource: '../src/Twig/Extension/*'
        tags: ['twig.extension']

    Softspring\UserBundle\Util\:
        resource: '../src/Util/*'

    # service aliases
    sfs_user.user_provider: '@Softspring\UserBundle\Provider\UserProvider'
    sfs_user.user_provider.email: '@Softspring\UserBundle\Provider\EmailProvider'
    sfs_user.user_provider.username: '@Softspring\UserBundle\Provider\UsernameProvider'