sfs_user_admin_invitations_list:
    controller: sfs_user.admin.invitation.controller::list
    path: /

sfs_user_admin_invitations_invite:
    controller: sfs_user.admin.invitation.controller::create
    path: /invite

sfs_user_admin_invitations_details:
    controller: sfs_user.admin.invitation.controller::read
    path: /{invitation}/details

sfs_user_admin_invitations_resend:
    controller: Softspring\UserBundle\Controller\Admin\InvitationsController::resendEmail
    path: /{invitation}/resend

sfs_user_admin_invitations_count_widget:
    controller: Softspring\UserBundle\Controller\Admin\InvitationsController::pendingCountWidget
    path: /_widget/pending-count
