sfs_user_admin_administrators_list:
    controller: Softspring\UserBundle\Controller\Admin\AdministratorsController::list
    path: /

sfs_user_admin_administrators_details:
    controller: Softspring\UserBundle\Controller\Admin\AdministratorsController::details
    path: /{administrator}/details


