sfs_user_admin_administrators_list:
    controller: sfs_user.admin.administrator.controller::list
    path: /

sfs_user_admin_administrators_details:
    controller: sfs_user.admin.administrator.controller::read
    path: /{administrator}/details

sfs_user_admin_administrators_demote_admin:
    controller: Softspring\UserBundle\Controller\Admin\AdministratorsController::demoteAdmin
    path: /{administrator}/demote-admin

