sfs_user_admin_users_list:
    controller: sfs_user.admin.user.controller::list
    path: /

sfs_user_admin_users_details:
    controller: sfs_user.admin.user.controller::read
    path: /{user}/details

sfs_user_admin_users_promote_admin:
    controller: Softspring\UserBundle\Controller\Admin\UsersController::promoteAdmin
    path: /{user}/promote-admin

sfs_user_admin_users_delete:
    controller: sfs_user.admin.user.controller::delete
    path: /{user}/delete
