sfs_user_admin_users_list:
    controller: Softspring\UserBundle\Controller\Admin\UsersController::list
    path: /

sfs_user_admin_users_details:
    controller: Softspring\UserBundle\Controller\Admin\UsersController::details
    path: /{user}/details

sfs_user_admin_users_promote_admin:
    controller: Softspring\UserBundle\Controller\Admin\UsersController::promoteAdmin
    path: /{user}/promote-admin
