sfs_user_register:
    path: /
    controller: Softspring\UserBundle\Controller\RegisterController::register

sfs_user_register_success:
    path: /welcome
    controller: Softspring\UserBundle\Controller\RegisterController::success

sfs_user_register_confirm:
    path: /{user}/confirm/{token}
    controller: Softspring\UserBundle\Controller\RegisterController::confirm