security:
    role_hierarchy:
        ROLE_ADMIN_USERS_RO:
            - PERMISSION_SFS_USER_ADMIN_USERS_LIST
            - PERMISSION_SFS_USER_ADMIN_USERS_DETAILS
        ROLE_ADMIN_USERS_RW:
            - ROLE_ADMIN_USERS_RO
            - PERMISSION_SFS_USER_ADMIN_USERS_DELETE
            - PERMISSION_SFS_USER_ADMIN_USERS_UPDATE
            - ROLE_ADMIN_ACCESS_HISTORY_LIST
        ROLE_ADMIN_ADMINISTRATORS_RO:
            - PERMISSION_SFS_USER_ADMIN_ADMINISTRATORS_LIST
            - PERMISSION_SFS_USER_ADMIN_ADMINISTRATORS_DETAILS
        ROLE_ADMIN_ADMINISTRATORS_RW:
            - ROLE_ADMIN_ADMINISTRATORS_RO
            - PERMISSION_SFS_USER_ADMIN_USERS_PROMOTE
            - PERMISSION_SFS_USER_ADMIN_ADMINISTRATORS_DEMOTE
            - PERMISSION_SFS_USER_ADMIN_ADMINISTRATORS_UPDATE
            - PERMISSION_SFS_USER_ADMIN_ADMINISTRATORS_DELETE
            - PERMISSION_SFS_USER_ADMIN_ADMINISTRATORS_INVITE
        ROLE_ADMIN_INVITATION_RO:
            - ROLE_ADMIN_INVITATIONS_LIST
            - ROLE_ADMIN_INVITATIONS_DETAILS