security:
    role_hierarchy:
        ROLE_ADMIN_USERS_RO:
            - ROLE_ADMIN_USERS_LIST
            - ROLE_ADMIN_USERS_DETAILS
        ROLE_ADMIN_USERS_RW:
            - ROLE_ADMIN_USERS_RO
            - ROLE_ADMIN_USERS_DELETE
            - ROLE_ADMIN_USERS_PROMOTE
            - ROLE_ADMIN_USERS_UPDATE
        ROLE_ADMIN_ADMINISTRATORS_RO:
            - ROLE_ADMIN_ADMINISTRATORS_LIST
            - ROLE_ADMIN_ADMINISTRATORS_DETAILS
        ROLE_ADMIN_ADMINISTRATORS_RW:
            - ROLE_ADMIN_ADMINISTRATORS_RO
            - ROLE_ADMIN_ADMINISTRATORS_DEMOTE
            - ROLE_ADMIN_ADMINISTRATORS_UPDATE
            - ROLE_ADMIN_ADMINISTRATORS_DELETE
            - ROLE_ADMIN_INVITATIONS_LIST
            - ROLE_ADMIN_INVITATIONS_DETAILS