security:
    role_hierarchy:
        ROLE_SFS_USER_ADMIN_USERS_RO:
            - PERMISSION_SFS_USER_ADMIN_USERS_LIST
            - PERMISSION_SFS_USER_ADMIN_USERS_DETAILS
        ROLE_SFS_USER_ADMIN_USERS_RW:
            - ROLE_SFS_USER_ADMIN_USERS_RO
            - PERMISSION_SFS_USER_ADMIN_USERS_DELETE
            - PERMISSION_SFS_USER_ADMIN_USERS_UPDATE
            - PERMISSION_SFS_USER_ADMIN_HISTORY_LIST
        ROLE_SFS_USER_ADMIN_ADMINISTRATORS_RO:
            - PERMISSION_SFS_USER_ADMIN_ADMINISTRATORS_LIST
            - PERMISSION_SFS_USER_ADMIN_ADMINISTRATORS_DETAILS
        ROLE_SFS_USER_ADMIN_ADMINISTRATORS_RW:
            - ROLE_SFS_USER_ADMIN_ADMINISTRATORS_RO
            - PERMISSION_SFS_USER_ADMIN_USERS_PROMOTE
            - PERMISSION_SFS_USER_ADMIN_ADMINISTRATORS_DEMOTE
            - PERMISSION_SFS_USER_ADMIN_ADMINISTRATORS_UPDATE
            - PERMISSION_SFS_USER_ADMIN_ADMINISTRATORS_DELETE
            - PERMISSION_SFS_USER_ADMIN_ADMINISTRATORS_INVITE
        ROLE_SFS_USER_ADMIN_INVITATION_RO:
            - PERMISSION_SFS_USER_ADMIN_INVITATIONS_LIST
            - PERMISSION_SFS_USER_ADMIN_INVITATIONS_DETAILS

        # DEPRECATED ROLES, WILL BE REMOVED IN 6.0
        ROLE_ADMIN_USERS_RO:
            - ROLE_SFS_USER_ADMIN_USERS_RO
        ROLE_ADMIN_USERS_RW:
            - ROLE_SFS_USER_ADMIN_USERS_RW
        ROLE_ADMIN_ADMINISTRATORS_RO:
            - ROLE_SFS_USER_ADMIN_ADMINISTRATORS_RO
        ROLE_ADMIN_ADMINISTRATORS_RW:
            - ROLE_SFS_USER_ADMIN_ADMINISTRATORS_RW
        ROLE_ADMIN_INVITATION_RO:
            - ROLE_SFS_USER_ADMIN_INVITATION_RO

        # DEPRECATED PERMISSIONS, WILL BE REMOVED IN 6.0
        # 5.1 REQUIRES PERMISSIONS-BUNDLE
        PERMISSION_SFS_USER_ADMIN_USERS_LIST:
            - ROLE_ADMIN_USERS_LIST
        PERMISSION_SFS_USER_ADMIN_USERS_DETAILS:
            - ROLE_ADMIN_USERS_DETAILS
        PERMISSION_SFS_USER_ADMIN_USERS_DELETE:
            - ROLE_ADMIN_USERS_DELETE
        PERMISSION_SFS_USER_ADMIN_USERS_UPDATE:
            - ROLE_ADMIN_USERS_UPDATE
        PERMISSION_SFS_USER_ADMIN_ADMINISTRATORS_LIST:
            - ROLE_ADMIN_ADMINISTRATORS_LIST
        PERMISSION_SFS_USER_ADMIN_ADMINISTRATORS_DETAILS:
            - ROLE_ADMIN_ADMINISTRATORS_DETAILS
        PERMISSION_SFS_USER_ADMIN_USERS_PROMOTE:
            - ROLE_ADMIN_USERS_PROMOTE
        PERMISSION_SFS_USER_ADMIN_ADMINISTRATORS_DEMOTE:
            - ROLE_ADMIN_ADMINISTRATORS_DEMOTE
        PERMISSION_SFS_USER_ADMIN_ADMINISTRATORS_UPDATE:
            - ROLE_ADMIN_ADMINISTRATORS_UPDATE
        PERMISSION_SFS_USER_ADMIN_ADMINISTRATORS_DELETE:
            - ROLE_ADMIN_ADMINISTRATORS_DELETE
        PERMISSION_SFS_USER_ADMIN_ADMINISTRATORS_INVITE:
            - ROLE_ADMIN_ADMINISTRATORS_INVITE
        PERMISSION_SFS_USER_ADMIN_INVITATIONS_LIST:
            - ROLE_ADMIN_INVITATIONS_LIST
        PERMISSION_SFS_USER_ADMIN_INVITATIONS_DETAILS:
            - ROLE_ADMIN_INVITATIONS_DETAILS
        PERMISSION_SFS_USER_ADMIN_HISTORY_LIST:
            - ROLE_ADMIN_ACCESS_HISTORY_LIST