services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Softspring\UserBundle\Form\Settings\ChangePasswordFormInterface:
        class: Softspring\UserBundle\Form\Settings\ChangePasswordForm

    Softspring\UserBundle\Controller\Settings\ChangePasswordController:
        public: true
        calls:
            - { method: setContainer, arguments: ['@service_container'] }
        arguments:
            $userManager: '@Softspring\UserBundle\Manager\UserManagerInterface'
            $changePasswordForm: '@Softspring\UserBundle\Form\Settings\ChangePasswordFormInterface'
