name: CI

on:
    push:
        branches: [ 6.0 ]
    pull_request:
        branches: [ 6.0 ]

permissions:
    contents: read

env:
    XDEBUG_MODE: coverage

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php-versions: [ '8.4' ]
                composer-prefer: [ '', '--prefer-lowest' ]

        steps:
            -   uses: actions/checkout@v6

            -   name: Install PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-versions }}
                    extensions: sqlite3, pdo_sqlite
                    coverage: xdebug
                    ini-values: "post_max_size=256M" #optional

            -   name: Check PHP Version
                run: php -v

            -   name: Validate composer.json and composer.lock
                run: composer validate --strict

            -   name: Cache Composer packages
                id: composer-cache
                uses: actions/cache@v5
                with:
                    path: vendor
                    key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
                    restore-keys: |
                        ${{ runner.os }}-php-

            -   name: Install dependencies
                run: COMPOSER_ROOT_VERSION=6.0.x-dev composer update --prefer-dist --no-interaction --no-progress ${{ matrix.composer-prefer }}

            -   name: Run phpstan
                run: ./vendor/bin/phpstan analyse

            -   name: Run tests
                run: ./vendor/bin/phpunit

            -   name: Code Style check
                run: ./vendor/bin/php-cs-fixer fix -v --diff --dry-run

            -   name: Check coverage report
                id: coverage_report
                run: |
                    if [ -f clover.xml ]; then
                        echo "has_clover=true" >> "$GITHUB_OUTPUT"
                    else
                        echo "has_clover=false" >> "$GITHUB_OUTPUT"
                    fi

            -   name: Upload coverage to Codecov
                if: matrix.composer-prefer == '' && steps.coverage_report.outputs.has_clover == 'true'
                uses: codecov/codecov-action@v5
                with:
                    token: ${{ secrets.CODECOV_TOKEN }}
                    files: clover.xml
